name: wkit-check-desktop
on: [push, workflow_dispatch, pull_request]

jobs:
  check-wkit-win:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Publish with Dotnet
      run: dotnet publish .\WolvenKit\WolvenKit.csproj -o .\publish -c Release

    - uses: actions/upload-artifact@v2
      with:
        name: WolvenKit Desktop
        path: .\publish
